apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/Tahira-Nawaz/Argocd-apps.git
      targetRevision: main
      path: applications/test-app
      helm:
        releaseName: test-app
        valueFiles:
          - $values/applications/test-app/values.yaml

    - repoURL: https://github.com/Tahira-Nawaz/Argocd-apps.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: test-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
